#!/bin/bash

case $(distro_check.sh) in
"Arch")
    yaourt -Ss $1
    ;;
"Debian" | "Ubuntu")
    aptitude search $1
    ;;
"Gentoo")
    eix $1
    ;;
"Fedora")
    yum search $1
    ;;
*)
    echo "Sorry, I don't know how to search on $(distro_check.sh)."
    ;;
esac
