#!/bin/bash
source ./distro_check.sh
distro_check

case ${PACKAGEMGR} in
    "yaourt")
        ${PACKAGEMGR} -Ss $1
        RETVAL=$?
        ;;
    "aptitude" | "yum")
        ${PACKAGEMGR} search $1
        RETVAL=$?
        ;;
    "emerge")
        ${PACKAGEMGR} -s $1
        RETVAL=$?
        ;;
    *)
        echo "Sorry, I don't know that one."
        RETVAL=1
        ;;
esac

exit ${RETVAL}
