#!/bin/bash

case $DISTRO in
"Arch")
    $PKGMGR -Rs $@
    ;;
"Debian" | "Ubuntu" | "LinuxMint")
    sudo $PKGMGR purge $@
    ;;
"Darwin")
	$PKGMGR uninstall $@
	;;
"Gentoo")
    sudo $PKGMGR --unmerge --ask $@
    ;;
"Fedora")
    sudo $PKGMGR erase $@
    ;;
"openSUSE")
    sudo $PKGMGR rm $@
    ;;
"VoidLinux")
    sudo xbps-remove -R $@
    ;;
*)
    echo "Sorry, I don't know how to remove packages on $DISTRO."
    ;;
esac
