#!/bin/bash

case $DISTRO in
"Arch")
    $PKGMGR -Rs $@
    ;;
"Debian" | "Ubuntu" | "LinuxMint")
    sudo $PKGMGR purge $@
    ;;
"Darwin")
	$PKGMGR uninstall $1
	;;
"Gentoo")
    sudo $PKGMGR --unmerge --ask $@
    ;;
"Fedora")
    sudo $PKGMGR erase $@
    ;;
*)
    echo "Sorry, I don't know how to remove packages on $DISTRO."
    ;;
esac
