#!/bin/bash

target=$1
action='start'

if [ $target == 'bai' ]; then
    target=$2
    action='stop'
elif [ $target == 'brb' ]; then
    target=$2
    action='restart'
fi

case $(distro_check.sh) in
"Arch")
    sudo /etc/rc.d/$target $action
    ;;
"Ubuntu")
    sudo service $target $action
    ;;
"Gentoo" | "Debian")
    sudo /etc/init.d/$target $action
    ;;
*)
    echo "Sorry, I don't know how to run services on $(distro_check.sh)."
    ;;
esac
