#!/bin/bash

target=$1
action='start'

if [ $2 ]; then
    target=$2
    case $1 in
    "bai")
        action='stop'
        ;;
    "brb")
        action='restart'
        ;;
    'on')
        action='enable'
        ;;
    'off')
        action='disable'
        ;;
    'wat' | 'wtf')
        action='disable'
        ;;
    *)
        action=$1
        ;;
    esac
fi

case $DISTRO in
"Ubuntu" | "LinuxMint")
    sudo service $target $action
    ;;
"Gentoo")
    sudo /etc/init.d/$target $action
    ;;
"VoidLinux")
    # VoidLinux uses something called runit
    # https://wiki.voidlinux.eu/Runit
    declare -A sv_actions
    sv_actions=([start]=up [stop]=down [restart]=restart [status]=status)
    if [[ ${sv_actions[$action]} ]]; then
        sudo sv ${sv_actions[$action]} $target
    fi
    ;;
*)
    # Just gonna try systemd
    sudo systemctl $action $target
    ;;
esac
