#!/bin/bash

case $(distro_check.sh) in
"Arch")
    yaourt -Syua --devel
    ;;
"Debian" | "Ubuntu")
    sudo aptitude update
    sudo aptitude upgrade --full-resolver
    ;;
"Gentoo")
    sudo emerge --sync && sudo layman -S && sudo eix-update
    sudo emerge --ask --verbose --update --newuse --deep --with-bdeps=y world
    ;;
"Fedora")
    sudo yum update
    ;;
*)
    echo "Sorry, I don't know how to update $(distro_check.sh)."
    ;;
esac
