#!/bin/bash

case $DISTRO in
"Arch")
    $PKGMGR -Syua --devel
    ;;
"Debian" | "Ubuntu" | "LinuxMint")
    sudo $PKGMGR update
    sudo $PKGMGR upgrade --full-resolver
    ;;
"Gentoo")
    sudo $PKGMGR --sync && sudo layman -S && sudo eix-update
    sudo $PKGMGR --ask --verbose --update --newuse --deep --with-bdeps=y world
    ;;
"Fedora")
    sudo $PKGMGR update
    ;;
*)
    echo "Sorry, I don't know how to update $DISTRO."
    ;;
esac
