#!/bin/bash

case $DISTRO in
"Arch")
    $PKGMGR -Qi $1
    ;;
"Debian" | "Ubuntu" | "LinuxMint")
    $PKGMGR show $1
    ;;
"Fedora" | "Darwin")
    $PKGMGR info $1
    ;;
"Gentoo")
    $PKGMGR -pv $1
    ;;
"VoidLinux")
    xbps-query $1
    ;;
*)
    echo "Sorry, I don't know how to inspect packages on $DISTRO."
    ;;
esac
