#!/bin/bash
source ./distro_check.sh
distro_check

if [ $EUID -ne 0 ]; then
    echo "update: I needz root plz."
    exit 1;
fi;

RETVAL=0
case ${PACKAGEMGR} in
    "yaourt")
        ${PACKAGEMGR} -Syua --devel
        RETVAL=$?
        ;;
    "aptitude")
        ${PACAKGEMGR} update
        if [ $? -eq 0 ]; then
            ${PACKAGEMGR} upgrade --full-resolver
        fi;
        RETVAL=$?
        ;;
    "yum")
        ${PACKAGEMGR} update
        RETVAL=$?
        ;;
    "emerge")
        echo "You're on your own here buddy..."
        RETVAL=1
        ;;
    *)
        echo "Sorry, I don't know that one."
        RETVAL=1
        ;;
esac

exit ${RETVAL}
