#!/bin/bash

case $DISTRO in
"Arch")
    $PKGMGR -S $@
    ;;
"Debian" | "Ubuntu" | "Fedora" | "LinuxMint" | "openSUSE")
    sudo $PKGMGR install $@
    ;;
"Darwin")
	$PKGMGR install $@
	;;
"Gentoo")
    sudo $PKGMGR -av $@
    ;;
"VoidLinux")
    sudo xbps-install -S $@
    ;;
*)
    echo "Sorry, I don't know how to install packages on $DISTRO."
    ;;
esac
