#!/bin/bash

case $(distro_check.sh) in
"Arch")
    yaourt -S $@
    ;;
"Debian" | "Ubuntu")
    sudo aptitude install $@
    ;;
"Fedora")
    sudo yum install $@
    ;;
*)
    echo "Sorry, I don't know that one."
    ;;
esac
