#!/bin/bash

case $(distro_check.sh) in
"Arch")
    yaourt -S $@
    ;;
"Debian" | "Ubuntu")
    sudo aptitude install $@
    ;;
"Gentoo")
    sudo emerge -av $@
    ;;
"Fedora")
    sudo yum install $@
    ;;
*)
    echo "Sorry, I don't know how to install packages on $(distro_check.sh)."
    ;;
esac
